# Generated by Django 3.0.6 on 2020-07-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.FloatField(default=10)),
                ('coins', models.IntegerField(default=10)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timers.Timer')),
            ],
        ),
    ]
