# Generated by Django 3.0.6 on 2020-08-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='timer',
        ),
    ]
