# Generated by Django 3.0.6 on 2020-08-14 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_time', models.IntegerField(default=25)),
                ('break_time', models.IntegerField(default=5)),
                ('curent_focus_time', models.IntegerField(default=25)),
                ('completed_focus_counter', models.IntegerField(default=0)),
                ('logged_focus_minutes', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='profiles.Profile')),
            ],
        ),
    ]
