# Generated by Django 3.0.6 on 2020-08-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='curent_focus_time',
            new_name='current_focus_time',
        ),
        migrations.AddField(
            model_name='timer',
            name='current_break_time',
            field=models.IntegerField(default=5),
        ),
    ]
