# Generated by Django 3.0.6 on 2020-08-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0002_auto_20200816_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='break_time',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='timer',
            name='current_break_time',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='timer',
            name='current_focus_time',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='timer',
            name='focus_time',
            field=models.IntegerField(default=1500),
        ),
    ]
