# Generated by Django 3.0.6 on 2020-08-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0003_auto_20200816_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='current_cycle',
            field=models.CharField(default='Focus', max_length=20),
        ),
    ]
