# Generated by Django 3.0.6 on 2020-08-08 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200808_2352'),
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='last_watered',
        ),
        migrations.AlterField(
            model_name='garden',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to='profiles.Profile'),
        ),
    ]
