# Generated by Django 3.0.6 on 2020-09-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('plants', '0001_initial'),
        ('gardens', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_water_counter', models.IntegerField(default=0)),
                ('last_watered', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=None)),
                ('column', models.IntegerField(default=None)),
                ('max_tool_attachments', models.IntegerField(default=3)),
                ('max_plant_attachments', models.IntegerField(default=1, editable=False)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='gardens.Garden')),
                ('plant', models.ManyToManyField(through='plots.Plant_Attachment', to='plants.Plant')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tool_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots.Plot')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Tool')),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='tool',
            field=models.ManyToManyField(through='plots.Tool_Attachment', to='tools.Tool'),
        ),
        migrations.AddField(
            model_name='plant_attachment',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots.Plot'),
        ),
    ]
