# Generated by Django 3.0.6 on 2020-08-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='column',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='plot',
            name='row',
            field=models.IntegerField(default=None),
        ),
    ]
