# Generated by Django 3.0.6 on 2020-07-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.AutoField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=50)),
                ('tool_description', models.CharField(max_length=500)),
                ('tool_type', models.CharField(max_length=100)),
                ('water_attribute', models.IntegerField()),
                ('growth_attribute', models.IntegerField()),
                ('time_before_decay_attribute', models.DurationField()),
                ('wither_attribute', models.IntegerField()),
                ('yield_attribute', models.IntegerField()),
                ('yield_price_attribute', models.IntegerField()),
                ('tool_price', models.IntegerField()),
            ],
        ),
    ]
