# Generated by Django 3.0.6 on 2020-08-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='growth_attribute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tool',
            name='time_before_decay_attribute',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tool',
            name='water_attribute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tool',
            name='wither_attribute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tool',
            name='yield_attribute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tool',
            name='yield_price_attribute',
            field=models.IntegerField(default=0),
        ),
    ]
