# Generated by Django 3.0.6 on 2020-07-21 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        ('gardens', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_water_counter', models.IntegerField()),
                ('last_watered', models.DateTimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Plot_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('max_tool_attachments', models.IntegerField(default=3)),
                ('max_plant_attachments', models.IntegerField(default=1, editable=False)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.Garden')),
                ('plant', models.ManyToManyField(through='plot_details.Plant_Attachment', to='plants.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Tool_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot_details.Plot_Detail')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Tool')),
            ],
        ),
        migrations.AddField(
            model_name='plot_detail',
            name='tool',
            field=models.ManyToManyField(through='plot_details.Tool_Attachment', to='tools.Tool'),
        ),
        migrations.AddField(
            model_name='plant_attachment',
            name='plot_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot_details.Plot_Detail'),
        ),
    ]
