# Generated by Django 3.0.6 on 2020-08-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=50)),
                ('plant_description', models.CharField(max_length=500)),
                ('plant_type', models.CharField(default='', max_length=20)),
                ('num_waters_to_harvest', models.IntegerField()),
                ('time_before_decay', models.DurationField(default=0)),
                ('wither_rate', models.IntegerField(default=0)),
                ('harvest_yield', models.IntegerField(default=0)),
                ('harvest_price', models.IntegerField(default=0)),
                ('plant_price', models.IntegerField(default=0)),
                ('plant_seed_energy', models.IntegerField(default=0)),
                ('water_energy', models.IntegerField(default=0)),
                ('harvest_energy', models.IntegerField(default=0)),
            ],
        ),
    ]
