# Generated by Django 3.0.6 on 2020-08-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='harvest_energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='harvest_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='harvest_yield',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_seed_energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='time_before_decay',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='wither_rate',
            field=models.IntegerField(default=0),
        ),
    ]
